name: ml4medical
channels:
  - pytorch
  - anaconda
  - bioconda
  - defaults
dependencies:
  - opencv
  - openslide-python
  - py-opencv
  - pixman=0.36.0
  - pandas
  - libiconv
  - matplotlib
  - numpy
  - scipy
  - tensorboard
  - pytorch
  - torchvision
  - cudatoolkit=10.2
  - pytorch-lightning
