name: ml4medical
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - opencv
  - openslide-python
  - py-opencv
  - pixman=0.36.0
  - pandas
  - libiconv
  - pytorch
  - torchvision => 0.8.2
  - matplotlib
  - numpy
  - scipy
  - tensorboard
  - cudatoolkit => 10.0
  - pytorch-lightning
